#define CAPS_WORD_IDLE_TIMEOUT 0
#define TAPPING_TERM 300
#define FLOW_TAP_TERM 150
#define SPECULATIVE_HOLD
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250
#define LEADER_NO_TIMEOUT
#define MASTER_RIGHT
// #define SPLIT_USB_DETECT

#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RIGHT_CTRL

// TODO -- Add to this if there are other combos that cause bad side effects
#define MODS_TO_NEUTRALIZE { \
    MOD_BIT(KC_LALT), \
    MOD_BIT(KC_LALT)|MOD_BIT(KC_LSFT), \
    MOD_BIT(KC_LALT)|MOD_BIT(KC_LCTL), \
    MOD_BIT(KC_LALT)|MOD_BIT(KC_LSFT)|MOD_BIT(KC_LCTL), \
    MOD_BIT(KC_LGUI), \
}

