#pragma once

#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 15 // Maybe play with this
#define WHEEL_EXTENDED_REPORT // Necessary to send wheel reports with 16-bit values to avoid overflowing

#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_DIVISOR_H 4.0 //120.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 4.0 //80.0
#define PLOOPY_DRAGSCROLL_INVERT

#define PLOOPY_DRAGSCROLL_SCROLLOCK