#pragma once

// #define POINTING_DEVICE_HIRES_SCROLL_ENABLE 0
// #define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 15

#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_DIVISOR_H 4.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 4.0
#define PLOOPY_DRAGSCROLL_INVERT

#define PLOOPY_DRAGSCROLL_SCROLLOCK